<?php	
	@session_start();
	// Guardamos cualquier error //
	ini_set('display_errors', 0);
	ini_set('memory_limit', '-1');
	error_reporting(E_ERROR | E_WARNING | E_PARSE | E_NOTICE);
	define('CONST',1);
	require('/var/www/html/login/config.php');
	require('/var/www/html/login/constantes.php');
	require('/var/www/html/login/db.php');
	require('/var/www/html/login/common.lib.php');

	$db = new SQL($dbhost, $dbname, $dbuser, $dbpass);
	$db2 = new SQL($pubProd['host'], $pubProd['db'], $pubProd['user'], $pubProd['pass']);
	$db3 = new SQL($pubDev01['host'], $pubDev01['db'], $pubDev01['user'], $pubDev01['pass']);

	$Domains = "missyusa.com
memurlar.net
mundopositivo.com.br
laverdadnoticias.com
merca20.com
correiobraziliense.com.br
youm7.com
rediff.com
ig.com.br
cifraclub.com.br
las2orillas.co
minuto30.com
larepublica.pe
elcolombiano.com
crhoy.com
elmostrador.cl
eluniversal.com.co
nouw.com
mi.tv
aristeguinoticias.com
canal1.com.co
vagalume.com.br
chinatimes.com
cooperativa.cl
prensa.com
dziennikwschodni.pl
tayyar.org
mundohispanico.com
yan.vn
otempo.com.br
biobiochile.cl
tempo.co
record.com.mx
jogosgratis.online
finanznachrichten.de
baenegocios.com
clicrbs.com.br
tvnotas.com.mx
letras.mus.br
tudogostoso.com.br
lebanonfiles.com
cgn.inf.br
calcuworld.com
cronica.com.ar
behindwoods.com
plantaoaovivo.com.br
vanguardia.com
diario16.com
diarioonline.com.br
lostiempos.com
joaobidu.com.br
theitaliantimes.it
lacapital.com.ar
elpais.com.co
infojobs.com.br
bestie.vn
hoy.com.py
tvazteca.com
elespanol.com
quadratin.com.mx
riovagas.com.br
aulafacil.com
indosport.com
diariocambio.com.mx
elespectador.com
montevideo.com.uy
lanacion.com.py
purepeople.com.br
minecrafteo.com
forum24.cz
culturacolectiva.com
solonoticias.com
ttshow.tw
lebanon24.com
mhoninoticias.com
tvguide.co.uk
revistabula.com
tribunaonline.com.br
eleconomista.com.mx
letras.com
conmishijos.com
hojeemdia.com.br
metro.pr
mixdeseries.com.br
em.com.br
midiario.com
deccanherald.com
ichacha.net
formulatv.com
diarioextra.com
diarioshow.com
columnacero.com
reportermt.com.br
noticiasaldiayalahora.co
gazetadopovo.com.br
lapatilla.com
minhavida.com.br
pilio.idv.tw
corriere.it
ecuavisa.com
repretel.com
uta-net.com
elsiglodetorreon.com.mx
cuentosparadormir.com
adnradio.cl
diario.mx
diariodepernambuco.com.br
lavozdealmeria.com
elblog.com
zoorprendente.com
lasestrellas.tv
vanguardia.com.mx
cartacapital.com.br
imageneseducativas.com
u-tv.ru
westca.com
letudiant.fr
20minutos.es
folhamax.com
guioteca.com
upsocl.com
pagina7.cl
theclinic.cl
unosantafe.com.ar
ilacweb.com
elespanol.com
historyplay.tv
lesiteinfo.com
teleamazonas.com
omgtw.com
periodicocentral.mx
santabanta.com
acordacidade.com.br
cronica.com.py
salon24.pl
latina.pe
sib.fm
sandesh.com
janamtv.com
ilustrado.cl
viapais.com.ar
malaymail.com
tichyseinblick.de
ecartelera.com
caracol.com.co
wradio.com.co
exitosanoticias.pe
konkurent.ru
orientacionandujar.es
cokitos.com
avito.ma
newindianexpress.com
twasul.info
receptite.com
labrujula24.com
entrepreneur.com
lahora.com.ec
lepoint.fr
superluchas.com
justcnw.com
bomb01.com
superela.com
fmdos.cl
cdn.com.do
vix.com
unoentrerios.com.ar
yucatan.com.mx
ciudad.com.ar
lasillarota.com
pueblaenlinea.com
lahora.gt
plox.com.br
mvsnoticias.com
fotech.cl
varelanoticias.com.br
dhnet.be
elwatannews.com
gtaall.com
infobae.com
ladiscusion.cl
eslamoda.com
vetogate.com
lance.com.br
muz-tv.ru
mejoress.com
latercera.com
eurogamer.pt
ejemplos.co
superhry.cz
elsiglo.com.pa
mexicodesconocido.com.mx
elmundo.cr
alairelibre.cl
sydneytoday.com
tv7dias.pt
maria.pt
chvnoticias.cl
pulzo.com
elfildeo.com
poresto.net
mediavida.com
administradores.com.br
versus.com.py
globo.com
elobservador.com.uy
m360.cl
bongda.com.vn
xeu.mx
elespanol.com
aastocks.com
febrayer.com
gazzetta.it
metroecuador.com.ec
eldeber.com.bo
eurogamer.es
laprensa.hn
metro951.com
internetpasoapaso.com
rioja2.com
der-betze-brennt.de
noticiassin.com
parallaximag.gr
everardoherrera.com
universoformulas.com
mi-rfc.com.mx
significadodossonhos.inf.br
independente.com.br
elpinguino.com
urgente24.com
excelsior.com.mx
rayanworld.com
elcaribe.com.do
republica.gt
revoluciontrespuntocero.mx
cuarteldelmetal.com
teledoce.com
culturizando.com
lateja.cr
frasesparawhats.com.br
qhubocali.com
seguimiento.co
definiciona.com
epop.my
facilisimo.com
lanetanoticias.com
soescola.com
lapatria.com
reforma.com
cinepremiere.com.mx
fifauteam.com
dondeir.com
frasesparainsta.com.br
economipedia.com
ensegundos.do
adorocinema.com
ecosdelcombeima.com
metromode.se
eurogamer.pl
twpkinfo.com
twice.se
laprensalibre.cr
elespanol.com
diariodamanha.com
paruvendu.fr
diaadia.com.pa
ensenada.net
metrojornal.com.br
milejemplos.com
elnorte.com
plangeneralcontable.com
tiempo.hn
viomundo.com.br
santamartaaldia.co
elsiglodedurango.com.mx
lafm.com.co
noticaribe.com.mx
mensagens.inf.br
publimetro.cl
memedroid.com
ecuagol.com
slunecnice.cz
tn.com.ar
testsworld.net
lanaciondigital.es
eldiario.net
dienanh.net
eldigitalcastillalamancha.es
studref.com
losreplicantes.com
radioagricultura.cl
rp10.com.br
publico.es
dinamani.com
hipertextual.com
peanutimes.com
netzkino.de
critica.com.pa
elpensante.com
futbol.com.uy
panamaamerica.com.pa
todo-mail.com
goio.news
anandabazar.com
pacozea.com
trespassosnews.com.br
stahuj.cz
ecuadorec.com
hola.com
laurag.tv
pantallazo.com.uy
argumentopolitico.org
elheraldo.hn
jenesaispop.com
eluniversal.cl
ecoosfera.com
emprendepyme.net
gfm.com.br
wowchakra.com
publimetro.com.mx
mundodeportivo.com
boxofficeindia.com
boxun.com
lalibre.be
mientrastantoenmexico.mx
nuevamujer.com
americatv.com.pe
eltrecetv.com.ar
elcondicional.com
thequint.com
extra.com.co
gamebrott.com
portalt5.com.br
solitariospider.org
paraguay.com
hsbnoticias.com
futuro.cl
anderlecht-online.be
jinriaozhou.com
gpucheck.com
elplacerdelalectura.com
japwind.com
goal.com
technical.city
xcatalunya.cat
diariolasamericas.com
conexioncapital.co
concierto.cl
eotimedopovo.com.br
nuevaya.com.ni
extraderondonia.com.br
caretas.pe
ver-taal.com
elembarazo.net
paraeles.pt
culturainquieta.com
lapadalapada.com.br
saberespractico.com
nacion.com
palmeirasonline.com
champion.gg
ederluiz.com.vc
superesportes.com.br
hnt.com.br
venezuelatuya.com
codigosi.com
emol.com
cokitos.pt
tresinteressant.com
estudopratico.com.br
eluniverso.com
justexw.com
finanz.ru
soyreferee.com
diez.hn
aulapt.org
komica.org
laopinion.com.co
paginasiete.bo
sidiario.com
terra.com.br
psicoactiva.com
lacuarta.com
convocatoriasdetrabajo.com
a8se.com
portalcaparao.com.br
kepoo.com
game735.com
eldelperiodico.com
eventossantamarta.com
laguiafemenina.com
cassilandianoticias.com.br
cn7.com.br
tnrelaciones.com
edenevaldoalves.com.br
publimetro.pe
channel-korea.com
lamejor.com.mx
mangaforever.net
cosmicbook.news
libero.pe
awsve.com
gotceleb.com
el-mexicano.com.mx
elperiscopio.cl
cryptodaily.co.uk
sinovision.net
23minutos.com
yavendras.com
guatemala.com
veintitantos.com
altonivel.com.mx
marketingdirecto.com
tiscali.cz
recursosep.com
easylife.tw
wh3.com.br
thetimes.cl
icarito.cl
canal4.tv.br
nawaret.com
futbolecuador.com
radiosago.cl
bekiapadres.com
popmundi.com.br
resultadoslotochile.com
sul21.com.br
cocinavital.mx
modelocurriculum.net
actividadesdeinfantilyprimaria.com
nvinoticias.com
piranot.com.br
gastronomia.com.uy
elinformadorchile.cl
mantosdofutebol.com.br
revistaronda.net
plantaobrasil.net
14ymedio.com
oestemania.net
noticiahoje.net
medicinanet.com.br
nfnoticias.com.br
iproup.com
soccer.ru
kraftfuttermischwerk.de
beautifulnara.com
kannadaprabha.com
novoextra.com.br
stoppapressarna.se
15a20.com.mx
folhadecampolargo.com.br
actiludis.com
ragalahari.com
cantika.com
elcomercio.pe
ac24.cz
significadoconcepto.com
tudn.mx
elsignificadode.com
quinto-poder.mx
lawebdelprogramador.com
diariolahuella.com
radiotapejara.com.br
netflu.com.br
gestion.pe
ocorreio.com.br
vipflash.de
truthdig.com
guiadelnino.com
frasesdeaniversario.com.br
seat61.com
astucesdegrandmere.net
diariobasta.com
centraldesermones.com
tusacordes.com
umuaramanews.com.br
newstechtime.com
ripollesdigital.cat
veuanoia.cat
bragancaempauta.com.br
altoastral.com.br
androidkosmos.de
itamarajunoticias.com.br
bekiapareja.com
todoconsejos.net
rcnradio.com
historia-biografia.com
dailycannon.com
elmananerodiario.com
nidbox.com
msnews.com.br
primeiroasaber.com.br
xiaomi4mi.com
babyhazelgames.com
novsport.com
uai.com.br
businessinsider.mx
hinchaamarillo.com
larepublica.cat
aldiario.com
jaenoticia.com.br
extra.ec
etapainfantil.com
pasala.com.mx
tinthethao.com.vn
deellas.com
football-addict.com
tec.com.pe
ecartelera.com.mx
mensagensdebomdia.com.br
meridiano.net
semprefamilia.com.br
newsland.com
radioactiva.cl
atomix.vg
bekia.es
ecbahia.com
wikiguate.com.gt
maxpark.com
bolsamania.com
viajarconmusica.com
elespanol.com
larecette.net
alvearya.com.ar
mentedidactica.com
mountainbike.es
movienco.co.uk
actualidadenfoco.com
axeso5.com
encancha.cl
meltoday.com
elnuevodiario.com.do
cinemascomics.com
pudahuel.cl
findrate.tw
diariodelcauca.com.co
revistacambrils.cat
areadepymes.com
abendzeitung-muenchen.de
teixeirahoje.com.br
radiotormentamx.com
ibahia.com
deguate.com
eldinamo.com
informatesalta.com.ar
vistazo.com
portalaconteceu.com.br
correio24horas.com.br
fcinter1908.it
linetv.tw
pipocasclub.com.br
pigoo.com
fronda.pl
martesfinanciero.com
antena2.com
zonared.com
ponteiro.com.br
formacion-dka.es
cincainews.com
americaeconomia.com
spinoff.com.br
bekiamascotas.com
ecuadorlegalonline.com
puthiyathalaimurai.com
bekiacocina.com
samakalikamalayalam.com
dalechivas.com
economiasimple.net
inspirahogar.com
peru21.pe
thismagazine.net
clasificadosvanguardia.com
planetatrucos.com
freestoriesforkids.com
pontaporainforma.com.br
holadoctor.com
diariodelsur.com.co
daleamerica.com
el3devuit.cat
heraldo.es
apronus.com
modelocarta.net
rockandpop.cl
cokitos.net
periodicolavoz.com.mx
mensagensdereflexao.com.br
desdeparaguay.com
sanateysana.com
promocionmusical.es
motociclismo.es
ellas.pa
enbuenasmanos.com
2001.com.ve
guiafitness.com
abriendobrecha.tv
ojo.pe
sentidodemujer.com
blogodorium.com.br
wikirock.net
agoravale.com.br
aeiou.pt
arecetas.com
elcalce.com
nupciasmagazine.com
quintanaroohoy.com
xeudeportes.mx
modelocontrato.net
mundoperro.net
educanimando.com
mdzol.com
lamega.com.co
corazon.cl
mulhersemphotoshop.com.br
cinehoyts.cl
plusesmas.com
amazonasnews.com
saludymente.net
elbocon.pe
viralistas.com
oggi.it
educapeques.com
iodonna.it
elblogdecineespanol.com
vrum.com.br
melhoresaplicativos.com.br
elfederal.com.ar
wapa.pe
mediterraneodigital.com
unicable.tv
kurzy.cz
depor.com
policialarevista.com
diarioav.com.br
semainesgrossesse.com
setmanarilebre.cat
futebol-addict.com
profelandia.com
musixmatch.com
refugiodelalma.com
aeplay.tv
vagabond.se
trome.pe
ciclismoafondo.es
lifetimeplay.tv
cuidadoinfantil.com
radiocacula.com.br

f1aldia.com
canalrcn.com
rincondelafe.com
novaconca.cat
mhonividente.mx
elfinancierocr.com
atitudeevisao.com.br
meridiano.net
sololistas.net
projekmm.com
diariolibre.com
frikipandi.com
motor16.com
liputan6.com
followthecolours.com.br
indulgexpress.com
perfectaidea.com
kpoponfire.com
modelofactura.net
logrosperu.com
televisa.com
reskyt.com
teepr.com
sportlife.es
bekiabelleza.com
pianetamilan.it
dt24.cz
ilposticipo.it
bekiahoroscopo.com
eltiempo.com
motoryracing.com
gooto.com
estrelando.com.br
elguardian.mx
radiobahiafm.com.br
qooah.com
iplocation.net
futboltotal.com.mx
publiboda.com
centralvingadores.com.br
pagereboot.com
guitarraviva.com
jeja.pl
clickpetroleoegas.com.br
masdeco.cl
revistaoxigeno.es
juegosagogo.com
contraquedadecabelo.com.br
fussball-addict.com
7x7.com
cassadigital.cat
teclado-pianovirtual.online
menzig.es
serautonomo.net
asivaespana.com
bekiapsicologia.com
yomeentreno.com
deporvito.com
netfla.com.br
infosaladillo.com.ar
radioacktiva.com
calcio-addict.com
gordelicias.biz
maviedechat.net
bekiafit.com
ohman.vn
revistashape.com.br
mujerde10.com
alertatolima.com
alertabogota.com
radioclubedopara.com.br
autopista.es
kapanlagi.com
queroviverbem.com.br
lugarcerto.com.br
mercantil.com
pideas.club
edexlive.com
mujer.com.pa
footballmanagerstory.com
plusmaths.com
cruger.com.br
babysitio.com
lasoposiciones.net
aficioncentral.com
corsedimoto.com
cosasdepeques.com
impacto.mx
manhuacu.com
tele-vall.com
calendariosep.mx
logic-immo.be
publimetro.co
exafm.com
elpais.com.uy
salud180.com
ideafixa.com
somgarrigues.cat
modelopresentacion.com
cinemaexpress.com
bandamax.tv
passioneinter.com
camilayahn.com.br
gnewsline.com
elintransigente.com
muysencillo.com
elbebe.com

fayerwayer.com
abcsaladillo.com.ar
aquehorajuega.co
akhbarak.net
2001online.com
20minutos.com
simparatodos.com.br
eldinamo.cl
nerdplanet.it
bekiamoda.com
tvrba.com.br
calendariodepago.com.ar
ahorrahoy.com
caretas.com.pe
entrevistadetrabajo.org
milideas.net
elvallenc.cat
escuelaenlanube.com
freesenzaglutine.it
actitudfem.com
phoneia.com
metroxmetro.com
qldtoday.com
forzaroma.info
sciaga.pl
televall.online
laspoesias.com
juvenews.eu
crescebene.com
cuantarazon.com
tripgotw.com
pulsourbano.com.ar
txapeldunak.com
pickyournewspaper.com
eldizque.com
vozperica.com
menzig.style
vrutal.com
physicsandmathstutor.com
ascodevida.com
mediagol.it
dineroenimagen.com
1text.com
radiolakalle.pe
comarquesdeponent.com
deperu.com
lleida.com
wefit.ru
eldeber.net
conmicelu.com
amica.it
mensagensreflexao.com.br
saltillo360.com
bollywoodlife.com
camarinvisita.cl
golssip.it
bekiahogar.com
news18nepal.com
feminiza.com
menzig.fit
nasepenize.cz
campechehoy.mx
itasportpress.it
futbolete.com
avisoseconomicos.com.mx
pagecup.com
cine3.com
cittaceleste.it
violanews.com
besame.fm
wallstreet-online.de
oronoticias.com.mx
radioimagina.cl
elpopular.pe
calcionapoli1926.it
pysznosci.pl
elperiodicodeportivo.com.co
nbamaniacs.com
cuantarazon.com
radioz.pe
memedeportes.com
cuantocabron.com
sportlife.com.br
eldoce.tv
finanzasblog.com.ar
deguate.net
toronews.net
mipielsana.com
paula.cl
eltravesser.cat
encontacto.mx
radioturquesa.fm
meganews.mx
saudebusiness365.com.br
tropicanafm.com
nursing.com.br
ilmilanista.it
oxigeno.fm
gadgetos.com
vistoenlasredes.com
mamirecetas.com
recetas.com.pa
saberesbreve.com
click.in
gruporivas.com.mx
artes9.com
portalvidasana.com
vitalfootball.co.uk
los40.com.co
vistoenlasredes.com
quieromibeca.com
tvshow.com.uy
agravidez.com
india.com
cine.com.pa
revistaalella.cat
semanaasemana.com
novatarrega.cat
ovaciondigital.com.uy
teimporta.com
ansocial.com.br
listamusicacriolla.com
deguate.com.gt
ascodevida.com
bitlydns.net
merdeka.com
revistabaixemporda.cat
the-news-mag.de
menzig.tech
eldeber.net
lahoravozdelmigrante.com
playhs.es
cartelera.com.uy
sgxniftydowfutureslive.com
otosia.com
imaginaradio.cat
paguemenos.com.br";

	$arDoms = explode('<br />', nl2br($Domains));
	foreach($arDoms as $Dom){
		$Dom = trim($Dom);
		
		$sql = "SELECT viewed_pages_per_month FROM website WHERE url LIKE '%$Dom%'";
		$VE = intval($db2->getOne($sql));
		if($VE == 0){
			$VE = 'undefined';
			$Nu++;
		}else{
			$N++;
		}
		
		echo "$VE \n";
	}
	
	
	echo "\n $N - $Nu";