CREATE TABLE `{{tablename}}` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idUser` int(11) NOT NULL,
  `idTag` int(11) NOT NULL,
  `idSite` int(11) DEFAULT NULL,
  `Domain` int(11) NOT NULL,
  `Country` int(11) NOT NULL,
  `Product` int(11) NOT NULL DEFAULT '0',
  `Impressions` int(11) NOT NULL DEFAULT '0',
  `Opportunities` int(11) NOT NULL DEFAULT '0',
  `formatLoads` int(11) NOT NULL DEFAULT '0',
  `Revenue` double(20,16) NOT NULL DEFAULT '0.0000000000000000',
  `Coste` double(20,16) NOT NULL DEFAULT '0.0000000000000000',
  `ExtraprimaP` double(4,2) NOT NULL DEFAULT '0.00',
  `Extraprima` double(20,16) NOT NULL DEFAULT '0.0000000000000000',
  `Clicks` int(11) NOT NULL DEFAULT '0',
  `Wins` int(11) NOT NULL DEFAULT '0',
  `adStarts` int(11) NOT NULL DEFAULT '0',
  `FirstQuartiles` int(11) NOT NULL DEFAULT '0',
  `MidViews` int(11) NOT NULL DEFAULT '0',
  `ThirdQuartiles` int(11) NOT NULL DEFAULT '0',
  `CompletedViews` int(11) NOT NULL DEFAULT '0',
  `timeAdded` int(11) NOT NULL,
  `lastUpdate` int(11) NOT NULL,
  `Date` date NOT NULL,
  `Hour` int(11) NOT NULL,
  `Manual` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `id` (`id`),
  KEY `idUser` (`idUser`),
  KEY `Date` (`Date`),
  KEY `idSite` (`idSite`),
  KEY `Hour` (`Hour`),
  KEY `Domain` (`Domain`),
  KEY `Country` (`Country`),
  KEY `idTag` (`idTag`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 PACK_KEYS=1 DELAY_KEY_WRITE=1 ROW_FORMAT=FIXED;